// flow-typed signature: 6d15b4cf9b1f4e5db44d91c558c6ad45
// flow-typed version: <<STUB>>/dev_v^0.1.3/flow_v0.46.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'dev'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'dev' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'dev/manager' {
  declare module.exports: any;
}

// Filename aliases
declare module 'dev/index' {
  declare module.exports: $Exports<'dev'>;
}
declare module 'dev/index.js' {
  declare module.exports: $Exports<'dev'>;
}
declare module 'dev/manager.js' {
  declare module.exports: $Exports<'dev/manager'>;
}
