// flow-typed signature: 2b4e797eaf83d06ced622a638e405967
// flow-typed version: <<STUB>>/react-burger-menu_v^2.1.6/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-burger-menu'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-burger-menu' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-burger-menu/dist/react-burger-menu' {
  declare module.exports: any;
}

declare module 'react-burger-menu/dist/react-burger-menu.min' {
  declare module.exports: any;
}

declare module 'react-burger-menu/lib/baseStyles' {
  declare module.exports: any;
}

declare module 'react-burger-menu/lib/BurgerIcon' {
  declare module.exports: any;
}

declare module 'react-burger-menu/lib/BurgerMenu' {
  declare module.exports: any;
}

declare module 'react-burger-menu/lib/CrossIcon' {
  declare module.exports: any;
}

declare module 'react-burger-menu/lib/menuFactory' {
  declare module.exports: any;
}

declare module 'react-burger-menu/lib/menus/bubble' {
  declare module.exports: any;
}

declare module 'react-burger-menu/lib/menus/elastic' {
  declare module.exports: any;
}

declare module 'react-burger-menu/lib/menus/fallDown' {
  declare module.exports: any;
}

declare module 'react-burger-menu/lib/menus/push' {
  declare module.exports: any;
}

declare module 'react-burger-menu/lib/menus/pushRotate' {
  declare module.exports: any;
}

declare module 'react-burger-menu/lib/menus/reveal' {
  declare module.exports: any;
}

declare module 'react-burger-menu/lib/menus/scaleDown' {
  declare module.exports: any;
}

declare module 'react-burger-menu/lib/menus/scaleRotate' {
  declare module.exports: any;
}

declare module 'react-burger-menu/lib/menus/slide' {
  declare module.exports: any;
}

declare module 'react-burger-menu/lib/menus/stack' {
  declare module.exports: any;
}

declare module 'react-burger-menu/lib/snapsvgImporter' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-burger-menu/dist/react-burger-menu.js' {
  declare module.exports: $Exports<'react-burger-menu/dist/react-burger-menu'>;
}
declare module 'react-burger-menu/dist/react-burger-menu.min.js' {
  declare module.exports: $Exports<'react-burger-menu/dist/react-burger-menu.min'>;
}
declare module 'react-burger-menu/lib/baseStyles.js' {
  declare module.exports: $Exports<'react-burger-menu/lib/baseStyles'>;
}
declare module 'react-burger-menu/lib/BurgerIcon.js' {
  declare module.exports: $Exports<'react-burger-menu/lib/BurgerIcon'>;
}
declare module 'react-burger-menu/lib/BurgerMenu.js' {
  declare module.exports: $Exports<'react-burger-menu/lib/BurgerMenu'>;
}
declare module 'react-burger-menu/lib/CrossIcon.js' {
  declare module.exports: $Exports<'react-burger-menu/lib/CrossIcon'>;
}
declare module 'react-burger-menu/lib/menuFactory.js' {
  declare module.exports: $Exports<'react-burger-menu/lib/menuFactory'>;
}
declare module 'react-burger-menu/lib/menus/bubble.js' {
  declare module.exports: $Exports<'react-burger-menu/lib/menus/bubble'>;
}
declare module 'react-burger-menu/lib/menus/elastic.js' {
  declare module.exports: $Exports<'react-burger-menu/lib/menus/elastic'>;
}
declare module 'react-burger-menu/lib/menus/fallDown.js' {
  declare module.exports: $Exports<'react-burger-menu/lib/menus/fallDown'>;
}
declare module 'react-burger-menu/lib/menus/push.js' {
  declare module.exports: $Exports<'react-burger-menu/lib/menus/push'>;
}
declare module 'react-burger-menu/lib/menus/pushRotate.js' {
  declare module.exports: $Exports<'react-burger-menu/lib/menus/pushRotate'>;
}
declare module 'react-burger-menu/lib/menus/reveal.js' {
  declare module.exports: $Exports<'react-burger-menu/lib/menus/reveal'>;
}
declare module 'react-burger-menu/lib/menus/scaleDown.js' {
  declare module.exports: $Exports<'react-burger-menu/lib/menus/scaleDown'>;
}
declare module 'react-burger-menu/lib/menus/scaleRotate.js' {
  declare module.exports: $Exports<'react-burger-menu/lib/menus/scaleRotate'>;
}
declare module 'react-burger-menu/lib/menus/slide.js' {
  declare module.exports: $Exports<'react-burger-menu/lib/menus/slide'>;
}
declare module 'react-burger-menu/lib/menus/stack.js' {
  declare module.exports: $Exports<'react-burger-menu/lib/menus/stack'>;
}
declare module 'react-burger-menu/lib/snapsvgImporter.js' {
  declare module.exports: $Exports<'react-burger-menu/lib/snapsvgImporter'>;
}
