// flow-typed signature: 6f4bc2e9a6642fc068f718f6021780c0
// flow-typed version: <<STUB>>/snoowrap_v^1.14.1/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'snoowrap'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'snoowrap' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'snoowrap/dist/constants' {
  declare module.exports: any;
}

declare module 'snoowrap/dist/create_config' {
  declare module.exports: any;
}

declare module 'snoowrap/dist/errors' {
  declare module.exports: any;
}

declare module 'snoowrap/dist/helpers' {
  declare module.exports: any;
}

declare module 'snoowrap/dist/objects/Comment' {
  declare module.exports: any;
}

declare module 'snoowrap/dist/objects/index' {
  declare module.exports: any;
}

declare module 'snoowrap/dist/objects/Listing' {
  declare module.exports: any;
}

declare module 'snoowrap/dist/objects/LiveThread' {
  declare module.exports: any;
}

declare module 'snoowrap/dist/objects/More' {
  declare module.exports: any;
}

declare module 'snoowrap/dist/objects/MultiReddit' {
  declare module.exports: any;
}

declare module 'snoowrap/dist/objects/PrivateMessage' {
  declare module.exports: any;
}

declare module 'snoowrap/dist/objects/RedditContent' {
  declare module.exports: any;
}

declare module 'snoowrap/dist/objects/RedditUser' {
  declare module.exports: any;
}

declare module 'snoowrap/dist/objects/ReplyableContent' {
  declare module.exports: any;
}

declare module 'snoowrap/dist/objects/Submission' {
  declare module.exports: any;
}

declare module 'snoowrap/dist/objects/Subreddit' {
  declare module.exports: any;
}

declare module 'snoowrap/dist/objects/UserList' {
  declare module.exports: any;
}

declare module 'snoowrap/dist/objects/VoteableContent' {
  declare module.exports: any;
}

declare module 'snoowrap/dist/objects/WikiPage' {
  declare module.exports: any;
}

declare module 'snoowrap/dist/Promise' {
  declare module.exports: any;
}

declare module 'snoowrap/dist/request_handler' {
  declare module.exports: any;
}

declare module 'snoowrap/dist/snoowrap' {
  declare module.exports: any;
}

declare module 'snoowrap/dist/xhr' {
  declare module.exports: any;
}

// Filename aliases
declare module 'snoowrap/dist/constants.js' {
  declare module.exports: $Exports<'snoowrap/dist/constants'>;
}
declare module 'snoowrap/dist/create_config.js' {
  declare module.exports: $Exports<'snoowrap/dist/create_config'>;
}
declare module 'snoowrap/dist/errors.js' {
  declare module.exports: $Exports<'snoowrap/dist/errors'>;
}
declare module 'snoowrap/dist/helpers.js' {
  declare module.exports: $Exports<'snoowrap/dist/helpers'>;
}
declare module 'snoowrap/dist/objects/Comment.js' {
  declare module.exports: $Exports<'snoowrap/dist/objects/Comment'>;
}
declare module 'snoowrap/dist/objects/index.js' {
  declare module.exports: $Exports<'snoowrap/dist/objects/index'>;
}
declare module 'snoowrap/dist/objects/Listing.js' {
  declare module.exports: $Exports<'snoowrap/dist/objects/Listing'>;
}
declare module 'snoowrap/dist/objects/LiveThread.js' {
  declare module.exports: $Exports<'snoowrap/dist/objects/LiveThread'>;
}
declare module 'snoowrap/dist/objects/More.js' {
  declare module.exports: $Exports<'snoowrap/dist/objects/More'>;
}
declare module 'snoowrap/dist/objects/MultiReddit.js' {
  declare module.exports: $Exports<'snoowrap/dist/objects/MultiReddit'>;
}
declare module 'snoowrap/dist/objects/PrivateMessage.js' {
  declare module.exports: $Exports<'snoowrap/dist/objects/PrivateMessage'>;
}
declare module 'snoowrap/dist/objects/RedditContent.js' {
  declare module.exports: $Exports<'snoowrap/dist/objects/RedditContent'>;
}
declare module 'snoowrap/dist/objects/RedditUser.js' {
  declare module.exports: $Exports<'snoowrap/dist/objects/RedditUser'>;
}
declare module 'snoowrap/dist/objects/ReplyableContent.js' {
  declare module.exports: $Exports<'snoowrap/dist/objects/ReplyableContent'>;
}
declare module 'snoowrap/dist/objects/Submission.js' {
  declare module.exports: $Exports<'snoowrap/dist/objects/Submission'>;
}
declare module 'snoowrap/dist/objects/Subreddit.js' {
  declare module.exports: $Exports<'snoowrap/dist/objects/Subreddit'>;
}
declare module 'snoowrap/dist/objects/UserList.js' {
  declare module.exports: $Exports<'snoowrap/dist/objects/UserList'>;
}
declare module 'snoowrap/dist/objects/VoteableContent.js' {
  declare module.exports: $Exports<'snoowrap/dist/objects/VoteableContent'>;
}
declare module 'snoowrap/dist/objects/WikiPage.js' {
  declare module.exports: $Exports<'snoowrap/dist/objects/WikiPage'>;
}
declare module 'snoowrap/dist/Promise.js' {
  declare module.exports: $Exports<'snoowrap/dist/Promise'>;
}
declare module 'snoowrap/dist/request_handler.js' {
  declare module.exports: $Exports<'snoowrap/dist/request_handler'>;
}
declare module 'snoowrap/dist/snoowrap.js' {
  declare module.exports: $Exports<'snoowrap/dist/snoowrap'>;
}
declare module 'snoowrap/dist/xhr.js' {
  declare module.exports: $Exports<'snoowrap/dist/xhr'>;
}
